INSERT INTO product (name, description, brand, price, category, stock_quantity, release_date, is_active) VALUES
                                                                                                             ('Espresso Roast Coffee', 'Dark, rich espresso roast with a deep flavor and notes of caramel', 'Starbucks', 450.00, 'Beverages', 80, '2023-01-10', TRUE),
                                                                                                             ('Swiss Chocolate', 'Luxurious milk chocolate made with premium Swiss ingredients', 'Lindt', 320.00, 'Confectionery', 150, '2023-02-14', FALSE),
                                                                                                             ('Extra Virgin Olive Oil', 'Cold-pressed olive oil with a rich flavor profile', 'Bertolli', 750.00, 'Groceries', 200, '2023-03-18', FALSE),
                                                                                                             ('Organic Green Tea', 'A soothing blend of organic green tea leaves', 'Twinings', 500.00, 'Beverages', 120, '2023-04-22', TRUE),
                                                                                                             ('Italian Pasta', 'Authentic Italian pasta made from 100% durum wheat', 'Barilla', 190.00, 'Groceries', 90, '2023-05-27', FALSE),
                                                                                                             ('Japanese Sake', 'Traditional Japanese rice wine with a smooth finish', 'Gekkeikan', 950.00, 'Beverages', 70, '2023-06-01', TRUE),
                                                                                                             ('French Brie Cheese', 'Creamy and soft Brie cheese from France', 'President', 850.00, 'Dairy', 65, '2023-07-06', FALSE),
                                                                                                             ('Belgian Waffles', 'Ready-to-eat Belgian waffles with a golden crust', 'Dr. Oetker', 240.00, 'Frozen Food', 110, '2023-08-11', FALSE),
                                                                                                             ('Korean Kimchi', 'Fermented Korean side dish made from napa cabbage and Korean radish', 'CJ Bibigo', 300.00, 'Groceries', 95, '2023-09-15', TRUE),
                                                                                                             ('Scottish Shortbread Cookies', 'Buttery and crumbly shortbread cookies from Scotland', 'Walkers', 280.00, 'Confectionery', 85, '2023-10-20', TRUE);
